name: AIOMod
author: BLOCKSTORM_
version: 1.0-PreAlpha
api: 3.0.0-Alpha12
main: AIOMod\Loader
commands:
  lock:
    default: op
    description: AIOMod Lock Command
  unlock: 
    default: op
    description: AIOMod unlock Command
  playerinfo: 
    default: op
    description: AIOMod playerinfo Command
  baninfo:
    default: op
    description: AIOMod baninfo
  locklist:
    default: op
    description: AIOMod locklist command
  notify:
    default: op
    description: turns system notifications on/off
